# Generated by Django 5.2.6 on 2025-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('apparel', 'Apparel'), ('shoes', 'Shoes'), ('football', 'Football'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('goalkeeper gear', 'Goalkeeper Gear'), ('collectibles', 'Collectibles')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
