# Generated by Django 5.2.6 on 2025-09-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
